
db_clients:
    # name: Name of the client,'default' by default
  - name: ''
    # rdbms: Server type, postgresql,mysql or sqlite3, "postgresql" by default
    rdbms: mysql
    # filename: Sqlite3 db file name
    # filename: '',
    # host: Server address,localhost by default
    host: 139.224.250.45
    # port: Server port, 5432 by default
    port: 3306
    # dbname: Database name
    dbname: ship
    # user: 'postgres' by default
    user: 'root'
    # passwd: '' by default
    passwd: 'tang044438'
    # is_fast: false by default, if it is true, the client is faster but user can't call
    # any synchronous interface of it.
    is_fast: false
    # client_encoding: The character set used by the client. it is empty string by default which 
    # means use the default character set.
    # client_encoding: '',
    # number_of_connections: 1 by default, if the 'is_fast' is true, the number is the number of  
    # connections per IO thread, otherwise it is the total number of all connections.  
    number_of_connections: 2
    # timeout: -1 by default, in seconds, the timeout for executing a SQL query.
    # zero or negative value means no timeout.
    timeout: -1
    # "auto_batch": this feature is only available for the PostgreSQL driver(version >= 14.0), see
    #  the wiki for more details.
    auto_batch: false
