//this file is generated by program automatically,don't modify it!
#include <drogon/DrTemplate.h>
class Base:public drogon::DrTemplate<Base>
{
public:
	Base(){};
	virtual ~Base(){};
	virtual std::string genText(const drogon::DrTemplateData &) override;
};
