//this file is generated by program automatically,don't modify it!
#include <drogon/DrTemplate.h>
class CameraPage:public drogon::DrTemplate<CameraPage>
{
public:
	CameraPage(){};
	virtual ~CameraPage(){};
	virtual std::string genText(const drogon::DrTemplateData &) override;
};
