//this file is generated by program automatically,don't modify it!
#include <drogon/DrTemplate.h>
class ChartPage:public drogon::DrTemplate<ChartPage>
{
public:
	ChartPage(){};
	virtual ~ChartPage(){};
	virtual std::string genText(const drogon::DrTemplateData &) override;
};
