//this file is generated by program automatically,don't modify it!
#include <drogon/DrTemplate.h>
class HomePage:public drogon::DrTemplate<HomePage>
{
public:
	HomePage(){};
	virtual ~HomePage(){};
	virtual std::string genText(const drogon::DrTemplateData &) override;
};
