//this file is generated by program(drogon_ctl) automatically,don't modify it!
#include "src/http/views/LoginPage.hpp"
#include <algorithm>
#include <deque>
#include <drogon/utils/OStringStream.h>
#include <iostream>
#include <list>
#include <map>
#include <queue>
#include <set>
#include <string>
#include <unordered_map>
#include <unordered_set>
#include <vector>
using namespace drogon;
std::string LoginPage::genText(const DrTemplateData &LoginPage_view_data)
{
    drogon::OStringStream LoginPage_tmp_stream;
    std::string layoutName { "" };
    LoginPage_tmp_stream << "<!DOCTYPE html>\n";
    LoginPage_tmp_stream << "<html lang=\"en\">\n";
    LoginPage_tmp_stream << "\n";
    LoginPage_tmp_stream << "<head>\n";
    LoginPage_tmp_stream << "	<meta charset=\"UTF-8\">\n";
    LoginPage_tmp_stream << "	<title>Hello</title>\n";
    LoginPage_tmp_stream << "	<link rel=\"shortcut icon\" href=\"E:/Code/CppTide/src/http/views/static/favicon.ico\">\n";
    LoginPage_tmp_stream << "	<link rel=\"stylesheet\" href=\"E:/Code/CppTide/src/http/views/static/bootstrap/bootstrap@4.6.min.css\">\n";
    LoginPage_tmp_stream << "	<link rel=\"stylesheet\" href=\"E:/Code/CppTide/src/http/views/static/css/init.css\">\n";
    LoginPage_tmp_stream << "</head>\n";
    LoginPage_tmp_stream << "\n";
    LoginPage_tmp_stream << "<body>\n";
    LoginPage_tmp_stream << "	<nav class=\"navbar navbar-expand-lg navbar-light bg-light\">\n";
    LoginPage_tmp_stream << "		<div class=\"container\">\n";
    LoginPage_tmp_stream << "			<a class=\"navbar-brand\" href=\"HomePage.html\">智能巡逻船控制后台</a>\n";
    LoginPage_tmp_stream << "			<button class=\"navbar-toggler collapsed\" type=\"button\" data-toggle=\"collapse\"\n";
    LoginPage_tmp_stream << "				data-target=\"#navbarSupportedContent\" aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\"\n";
    LoginPage_tmp_stream << "				aria-label=\"Toggle navigation\">\n";
    LoginPage_tmp_stream << "				<span class=\"navbar-toggler-icon\"></span>\n";
    LoginPage_tmp_stream << "			</button>\n";
    LoginPage_tmp_stream << "			<div class=\"navbar-collapse collapse show\" id=\"navbarSupportedContent\" style>\n";
    LoginPage_tmp_stream << "				<ul class=\"navbar-nav mr-auto\">\n";
    LoginPage_tmp_stream << "					<li class=\"nav-item active\">\n";
    LoginPage_tmp_stream << "						<a class=\"nav-link\" href=\"HomePage.html\">首页 <span class=\"sr-only\">(current)</span></a>\n";
    LoginPage_tmp_stream << "					</li>\n";
    LoginPage_tmp_stream << "					<li class=\"nav-item\">\n";
    LoginPage_tmp_stream << "						<a class=\"nav-link\" href=\"CameraPage.html\">视频显示</a>\n";
    LoginPage_tmp_stream << "					</li>\n";
    LoginPage_tmp_stream << "					<li class=\"nav-item\">\n";
    LoginPage_tmp_stream << "						<a class=\"nav-link\" href=\"MapPage.html\">地图显示</a>\n";
    LoginPage_tmp_stream << "					</li>\n";
    LoginPage_tmp_stream << "					<li class=\"nav-item\">\n";
    LoginPage_tmp_stream << "						<a class=\"nav-link\" href=\"ChartPage.html\">水质数据显示</a>\n";
    LoginPage_tmp_stream << "					</li>\n";
    LoginPage_tmp_stream << "				</ul>\n";
    LoginPage_tmp_stream << "				<ul class=\"navbar-nav\">\n";
    LoginPage_tmp_stream << "					<li class=\"nav-item\">\n";
    LoginPage_tmp_stream << "						<span class=\"nav-link\">Hello World</span>\n";
    LoginPage_tmp_stream << "					</li>\n";
    LoginPage_tmp_stream << "					<li class=\"nav-item\">\n";
    LoginPage_tmp_stream << "						<a class=\"nav-link\" href=\"#\">退出登录</a>\n";
    LoginPage_tmp_stream << "					</li>\n";
    LoginPage_tmp_stream << "					<li class=\"nav-item\">\n";
    LoginPage_tmp_stream << "						<a class=\"nav-link\" href=\"LoginPage.html\">登录</a>\n";
    LoginPage_tmp_stream << "					</li>\n";
    LoginPage_tmp_stream << "					<li class=\"nav-item\">\n";
    LoginPage_tmp_stream << "						<a class=\"nav-link\" href=\"RegisterPage.html\">注册</a>\n";
    LoginPage_tmp_stream << "					</li>\n";
    LoginPage_tmp_stream << "				</ul>\n";
    LoginPage_tmp_stream << "			</div>\n";
    LoginPage_tmp_stream << "		</div>\n";
    LoginPage_tmp_stream << "	</nav>\n";
    LoginPage_tmp_stream << "\n";
    LoginPage_tmp_stream << "	<div class=\"container\"></div>\n";
    LoginPage_tmp_stream << "\n";
    LoginPage_tmp_stream << "	<div class=\"row mt-4\">\n";
    LoginPage_tmp_stream << "		<div class=\"col\"></div>\n";
    LoginPage_tmp_stream << "		<div class=\"col\">\n";
    LoginPage_tmp_stream << "			<form action=\"http://127.0.0.1:8000/login\" method=\"POST\">\n";
    LoginPage_tmp_stream << "				<div class=\"form-group\">\n";
    LoginPage_tmp_stream << "					<label for=\"exampleInputEmail1\">邮箱</label>\n";
    LoginPage_tmp_stream << "					<input type=\"email\" class=\"form-control\" id=\"exampleInputEmail1\" aria-describedby=\"emailHelp\"\n";
    LoginPage_tmp_stream << "						name=\"email\">\n";
    LoginPage_tmp_stream << "					<small id=\"emailHelp\" class=\"form-text text-muted\">我们不会把邮箱用于其他用途</small>\n";
    LoginPage_tmp_stream << "				</div>\n";
    LoginPage_tmp_stream << "				<div class=\"form-group\">\n";
    LoginPage_tmp_stream << "					<label for=\"exampleInputPassword1\">密码</label>\n";
    LoginPage_tmp_stream << "					<input type=\"password\" class=\"form-control\" id=\"exampleInputPassword1\" name=\"password\">\n";
    LoginPage_tmp_stream << "				</div>\n";
    LoginPage_tmp_stream << "\n";
    LoginPage_tmp_stream << "				<div class=\"form-group\">\n";
    LoginPage_tmp_stream << "					<div class=\"text-danger\"></div>\n";
    LoginPage_tmp_stream << "				</div>\n";
    LoginPage_tmp_stream << "\n";
    LoginPage_tmp_stream << "				<div class=\"form-group\">\n";
    LoginPage_tmp_stream << "					<button type=\"submit\" class=\"btn btn-primary btn-block\">立即登录</button>\n";
    LoginPage_tmp_stream << "				</div>\n";
    LoginPage_tmp_stream << "\n";
    LoginPage_tmp_stream << "\n";
    LoginPage_tmp_stream << "			</form>\n";
    LoginPage_tmp_stream << "		</div>\n";
    LoginPage_tmp_stream << "		<div class=\"col\"></div>\n";
    LoginPage_tmp_stream << "	</div>\n";
    LoginPage_tmp_stream << "</body>\n";
    LoginPage_tmp_stream << "\n";
    LoginPage_tmp_stream << "</html>\n";
    if (layoutName.empty()) {
        std::string ret { std::move(LoginPage_tmp_stream.str()) };
        return ret;
    } else {
        auto templ = DrTemplateBase::newTemplate(layoutName);
        if (!templ) return "";
        HttpViewData data = LoginPage_view_data;
        auto str          = std::move(LoginPage_tmp_stream.str());
        if (!str.empty() && str[str.length() - 1] == '\n') str.resize(str.length() - 1);
        data[""] = std::move(str);
        return templ->genText(data);
    }
}
