//this file is generated by program automatically,don't modify it!
#include <drogon/DrTemplate.h>
class MapPage:public drogon::DrTemplate<MapPage>
{
public:
	MapPage(){};
	virtual ~MapPage(){};
	virtual std::string genText(const drogon::DrTemplateData &) override;
};
