//this file is generated by program automatically,don't modify it!
#include <drogon/DrTemplate.h>
class RegisterPage:public drogon::DrTemplate<RegisterPage>
{
public:
	RegisterPage(){};
	virtual ~RegisterPage(){};
	virtual std::string genText(const drogon::DrTemplateData &) override;
};
